# ~/.tmuxinator/default.yml

name: default
root: ~/

# The two options below are needed in order to work integrate with iTerm2 properly
attach: false
on_project_exit: tmux -CC attach

windows:
  - boris_cluster:
      layout: tiled
      pre:
        - tab_color 160 100 100
        - echo Set the color
        - clear
      panes:
        - ssh someserver
        - ssh someserver
        - ssh someserver
  - colo_control:
      layout: tiled
      pre:
        - tab_color 100 120 85
        - echo Set the color
        - clear
      panes:
        - ssh someserver
        - ssh someserver
  - home_router:
       layout: tiled
       pre:
         - tab-color 90 90 90
         - echo Set the color
       panes:
         - ressh admin@homerouter
  - solutions_git:
      layout: tiled
      pre:
        - tab_color 80 100 130
        - echo Set the color
        - clear
      panes:
        - cd ~/Sources/solutions
  - dio:
      layout: tiled
      pre:
        - tab_color 110 50 150
        - echo Set the color
        - clear
      panes:
        - cd ~/Sources/dio
  - misc_git:
      layout: tiled
      pre:
        - tab_color 65 45 35
        - echo Set the color
        - clear
      panes:
        - cd ~/Sources/
  - aristotle:
      layout: tiled
#      pre:
#        - tab-color 77 77 77
#        - echo Set the color
      panes:
        -
  - aristotle:
      layout: tiled
#      pre:
#        - tab-color 77 77 77
#        - echo Set the color
      panes:
        -
  - aristotle:
      layout: tiled
#      pre:
#        - tab-color 77 77 77
#        - echo Set the color
      panes:
        -
